package at.ac.fhvie.s24.swpj4bb.touristoffice.demo.business.entity;

import at.ac.fhvie.s24.swpj4bb.touristoffice.demo.business.constants.Category;
import lombok.*;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Hotel entity
 */
@Entity

// The following annotations are for Lombok that we do not have to create the Getters,
// a constructor with all arguments, a constructor with no arguments an a toString() Methos
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class Hotel {
  // the variable id is marked as the primary key in the database table
  @Id
  // The primary key is generated by the database via an autoincrement field
  // See https://thoughts-on-java.org/jpa-generate-primary-keys/ for alternatives

  // Codeanfang_Achill_Hotel_Entity
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "id", updatable = false, nullable = false)
  private int id;

  private Category category;

  private String name;
  private String owner;
  private String contact;
  private String address;
  private String city;
  // Mapping between database field and variable
  @Column(name = "zip")
  private String cityCode;
  private String phone;
  // Mapping between database field and variable
  @Column(name = "rooms")
  private int noRooms;
  // Mapping between database field and variable
  @Column(name = "beds")
  private int noBeds;

  //Codestart_#10_Dominik_30.03.2024_Add attributes (URL, family-friendly, dog-friendly, Spa, Fitness) to master data
  private String  url;
  @Column(name = "family_friendly")
  private boolean familyFriendly;
  @Column(name = "dog_friendly")
  private boolean dogFriendly;
  private boolean spa;
  private boolean fitness;
  //Codeend_#10_Dominik_30.03.2024_Add attributes (URL, family-friendly, dog-friendly, Spa, Fitness) to master data

  //Codestart_Dominik_30.03.2024_Added variables e-mail_address and subscribed
  @Column(name = "email_address")
  private String  emailAddress;
  private boolean subscribed;
  //Codeend_Dominik_30.03.2024_Added variables e-mail_address and subscribed
  private boolean deleted;


  public static HotelBuilder builder() {
    return new HotelBuilder();
  }

  public Hotel updateWith(final Hotel other) {
    this.category = other.category;
    this.name = other.name;
    this.owner = other.owner;
    this.contact = other.contact;
    this.address = other.address;
    this.city = other.city;
    this.cityCode = other.cityCode;
    this.phone = other.phone;
    this.noRooms = other.noRooms;
    this.noBeds = other.noBeds;

    //Codestart_#10_Dominik_30.03.2024_Req: Add attributes (URL, family-friendly, dog-friendly, Spa, Fitness) to master data
    this.url = other.url;
    this.familyFriendly = other.familyFriendly;
    this.dogFriendly = other.dogFriendly;
    this.spa = other.spa;
    this.fitness = other.fitness;
    //Codeend_#10_Dominik_30.03.2024_Req: Add attributes (URL, family-friendly, dog-friendly, Spa, Fitness) to master data

    //Codestart_Dominik_30.03.2024_Added variables e-mail_address and subscribed
    this.emailAddress = other.emailAddress;
    this.subscribed = other.subscribed;
    //Codeend_Dominik_30.03.2024_Added variables e-mail_address and subscribed
    this.deleted = other.deleted;
    return this;
  }
  public static class HotelBuilder {
    private int id;
    private Category category;
    private String name;
    private String owner;
    private String contact;
    private String address;
    private String city;
    private String cityCode;
    private String phone;
    private int noRooms;
    private int noBeds;

    //Codestart_#10_Dominik_30.03.2024_Req: Add attributes (URL, family-friendly, dog-friendly, Spa, Fitness) to master data
    private String url;
    private boolean familyFriendly;
    private boolean dogFriendly;
    private boolean spa;
    private boolean fitness;
    //Codeend_#10_Dominik_30.03.2024_Add attributes (URL, family-friendly, dog-friendly, Spa, Fitness) to master data

    //Codestart_Dominik_30.03.2024_Added variables e-mail_address and subscribed
    private String  emailAddress;
    private boolean subscribed;
    //Codeend_Dominik_30.03.2024_Added variables e-mail_address and subscribed
    private boolean deleted;

    public HotelBuilder() {
    }

    @SuppressWarnings("checkstyle:hiddenfield")
    public HotelBuilder id(final int id) {
      this.id = id;
      return this;
    }

    @SuppressWarnings("checkstyle:hiddenField")
    public HotelBuilder category(final Category category) {
      this.category = category;
      return this;
    }

    @SuppressWarnings("checkstyle:hiddenField")
    public HotelBuilder name(final String name) {
      this.name = name;
      return this;
    }

    @SuppressWarnings("checkstyle:hiddenField")
    public HotelBuilder owner(final String owner) {
      this.owner = owner;
      return this;
    }

    @SuppressWarnings("checkstyle:hiddenField")
    public HotelBuilder contact(final String contact) {
      this.contact = contact;
      return this;
    }

    @SuppressWarnings("checkstyle:hiddenField")
    public HotelBuilder address(final String address) {
      this.address = address;
      return this;
    }

    @SuppressWarnings("checkstyle:hiddenField")
    public HotelBuilder city(final String city) {
      this.city = city;
      return this;
    }

    @SuppressWarnings("checkstyle:hiddenField")
    public HotelBuilder cityCode(final String cityCode) {
      this.cityCode = cityCode;
      return this;
    }

    @SuppressWarnings("checkstyle:hiddenField")
    public HotelBuilder phone(final String phone) {
      this.phone = phone;
      return this;
    }

    @SuppressWarnings("checkstyle:hiddenField")
    public HotelBuilder noRooms(final int noRooms) {
      this.noRooms = noRooms;
      return this;
    }

    @SuppressWarnings("checkstyle:hiddenField")
    public HotelBuilder noBeds(final int noBeds) {
      this.noBeds = noBeds;
      return this;
    }

    //Codestart_#10_Dominik_30.03.2024_Add attributes (URL, family-friendly, dog-friendly, Spa, Fitness) to master data

    @SuppressWarnings("checkstyle:hiddenField")
    public HotelBuilder url(final String url) {
      this.url = url;
      return this;
    }

    @SuppressWarnings("checkstyle:hiddenField")
    public HotelBuilder familyFriendly(final boolean familyFriendly) {
      this.familyFriendly = familyFriendly;
      return this;
    }

    @SuppressWarnings("checkstyle:hiddenField")
    public HotelBuilder dogFriendly(final boolean dogFriendly) {
      this.dogFriendly = dogFriendly;
      return this;
    }

    @SuppressWarnings("checkstyle:hiddenField")
    public HotelBuilder spa(final boolean spa) {
      this.spa = spa;
      return this;
    }

    @SuppressWarnings("checkstyle:hiddenField")
    public HotelBuilder fitness(final boolean fitness) {
      this.fitness = fitness;
      return this;
    }
    //Codeend_#10_Dominik_30.03.2024_Add attributes (URL, family-friendly, dog-friendly, Spa, Fitness) to master data

    //Codestart_Dominik_30.03.2024_Added variables e-mail_address and subscribed
    @SuppressWarnings("checkstyle:hiddenField")
    public HotelBuilder emailAddress(final String emailAddress) {
      this.emailAddress = emailAddress;
      return this;
    }

      @SuppressWarnings("checkstyle:hiddenField")
      public HotelBuilder subscribed(final boolean subscribed) {
        this.subscribed = subscribed;
        return this;
      }
    //Codeend_Dominik_30.03.2024_Added variables e-mail_address and subscribed

    @SuppressWarnings("checkstyle:hiddenField")
    public HotelBuilder deleted(final boolean deleted) {
      this.deleted = deleted;
      return this;
      }
    public Hotel build() {
      return new Hotel(id, category, name, owner, contact, address, city, cityCode, phone,
          noRooms, noBeds, url, familyFriendly, dogFriendly, spa, fitness, emailAddress, subscribed, deleted);
    }

    public String toString() {
      return "Hotel.HotelBuilder(id=" + this.id + ", category="
          + this.category + ", name=" + this.name + ", owner=" + this.owner
          + ", contact=" + this.contact + ", address=" + this.address + ", city="
          + this.city + ", cityCode=" + this.cityCode + ", phone=" + this.phone
          + ", noRooms=" + this.noRooms + ", noBeds=" + this.noBeds
              //Codestart_#10_Dominik_30.03.2024_Add attributes (URL, family-friendly, dog-friendly, Spa, Fitness) to master data
              + ", url=" + this.url + ", familyFriendly=" + this.familyFriendly
              + ", dogFriendly=" + this.dogFriendly + ", spa=" + this.spa + ", fitness=" + this.fitness
              //Codeend_#10_Dominik_30.03.2024_Add attributes (URL, family-friendly, dog-friendly, Spa, Fitness) to master data
              //Codestart_Dominik_30.03.2024_Added variables e-mail_address and subscribed
              + ", emailAddress=" + this.emailAddress + ", subscribed=" + this.subscribed+ ", deleted=" + this.deleted
              //Codeend_Dominik_30.03.2024_Added variables e-mail_address and subscribed
              + ")";
    }
  }
}
