package at.ac.fhvie.s24.swpj4bb.touristoffice.demo.business.entity;

import at.ac.fhvie.s24.swpj4bb.touristoffice.demo.business.constants.Category;
import at.ac.fhvie.s24.swpj4bb.touristoffice.demo.business.constants.Nationality;
import lombok.*;

import javax.persistence.*;

/**
 * Occupancy entity
 */


@Entity

// The following annotations are for Lombok that we do not have to create the Getters,
// a constructor with all arguments, a constructor with no arguments an a toString() Methos
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@ToString
//  Codeanfang_Achill_22.03.2024/16.04.2024_Occupancy
public final class Occupancy {

    //  Codeanfang_Achill_22.03.2024_Occupancy

    // the variable id is marked as the primary key in the database table
    @Id
    // The primary key is generated by the database via an autoincrement field
    // See https://thoughts-on-java.org/jpa-generate-primary-keys/ for alternatives
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "occupancy_id", updatable = false, nullable = false)
    private int occupancyid;

    // Codeanfang_Nikola:07.04.2024_HotelEntity
    @ManyToOne
    @JoinColumn(name = "id")
    private Hotel id;
    // Codeende_Nikola:07.04.2024_HotelEntity

    private int rooms;

    private int usedrooms;

    private int beds;

    private int usedbeds;

    private int year;

    private int month;

    // Codeanfang_Anes:22.04.2024_Nationality
    private Nationality nationality;


    public static OccupancyBuilder builder() {
        return new OccupancyBuilder();
    }

    public Occupancy updateWith(final Occupancy other) {
        this.rooms = other.rooms;
        this.usedrooms = other.usedrooms;
        this.beds = other.beds;
        this.usedbeds = other.usedbeds;
        this.year = other.year;
        this.month = other.month;
        this.id = other.id;
        // Codeanfang_Anes:22.04.2024_Nationality
        this.nationality = other.nationality;
        // Codeende_Anes_22.04.2024_Nationality
        return this;
    }


    public static class OccupancyBuilder {
        private int occupancyid;
        private Hotel id;
        private int rooms;
        private int usedrooms;
        private int beds;
        private int usedbeds;
        private int year;
        private int month;
        private Nationality nationality;

        public OccupancyBuilder() {
        }

        public OccupancyBuilder occupancyid(final int occupancyid) {
            this.occupancyid = occupancyid;
            return this;
        }
        public OccupancyBuilder id(final Hotel id) {
            this.id = id;
            return this;
        }

        @SuppressWarnings("checkstyle:hiddenField")
        public OccupancyBuilder rooms(final int rooms) {
            this.rooms = rooms;
            return this;
        }

        @SuppressWarnings("checkstyle:hiddenField")
        public OccupancyBuilder usedRooms(final int usedrooms) {
            this.usedrooms = usedrooms;
            return this;
        }

        @SuppressWarnings("checkstyle:hiddenField")
        public OccupancyBuilder beds(final int beds) {
            this.beds = beds;
            return this;
        }

        @SuppressWarnings("checkstyle:hiddenField")
        public OccupancyBuilder usedBeds(final int usedbeds) {
            this.usedbeds = usedbeds;
            return this;
        }


        @SuppressWarnings("checkstyle:hiddenField")
        public OccupancyBuilder year(final int year) {
            this.year = year;
            return this;
        }

        @SuppressWarnings("checkstyle:hiddenField")
        public OccupancyBuilder month(final int month) {
            this.month = month;
            return this;
        }

        // Codeanfang_Anes:22.04.2024_Nationality
        @SuppressWarnings("checkstyle:hiddenField")
        public OccupancyBuilder nationality(final Nationality nationality) {
            this.nationality = nationality;
            return this;
        }
        // Codeende_Anes_22.04.2024_Nationality
        public Occupancy build() {
            return new Occupancy(occupancyid, id, rooms, usedrooms, beds, usedbeds, year, month, nationality);
        }
        public String toString() {
            return "Occupancy.OccupancyBuilder(occupancyid=" + this.occupancyid + ", rooms=" + this.rooms + ", usedRooms="
                    + this.usedrooms + ", beds=" + this.beds + ", usedBeds=" + this.usedbeds
                    + ", year=" + this.year + ", month=" + this.month + ", nationality=" + this.nationality + ")";
        }
    }
}
//  Codeende_Achill_24.03.2024/16.04.2024_Occupancy
